name = "mistllc-backend-worker"
main = "./backend/dist/index.ts"
compatibility_date = "2025-08-03"
compatibility_flags = [ "nodejs_compat" ]
account_id = "55221ae8c513e4288ff1986ad16ae04d"
binding = "mistllc"
id = "2d250836cc7d4adebb9d6a5968671077"

[vars]
VITE_API_BASE = "https://mistllc-backend-worker.jacobnixon59.workers.dev"


[placement]
mode = "smart"

