name = "mistllc-backend"
main = "src/index.ts"
compatibility_date = "2025-08-23"

[[d1_databases]]
binding = "DB"
database_name = "mistllc_db"
database_id = "8a00ac76-0737-4110-86e1-1c89e06f2421"

[[vars]]
Route= "production"
Api= "api.mistllc.org"
